apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-linktree
  namespace: nextum-prod # <--- Fundamental para que el Ingress lo vea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-linktree
  template:
    metadata:
      labels:
        app: nextjs-linktree
    spec:
      containers:
      - name: linktree-container
        # REEMPLAZA [TU_PROJECT_ID] por el tuyo real
        image: us-central1-docker.pkg.dev/[TU_PROJECT_ID]/nextum-repo/nextjs-app:latest
        ports:
        - containerPort: 3000 # <--- El puerto real de Next.js
---
apiVersion: v1
kind: Service
metadata:
  name: nextumlabs-backend-service
  namespace: nextum-prod # <--- Mismo namespace
spec:
  type: NodePort
  selector:
    app: nextjs-linktree # <--- Debe coincidir con el label del Deployment arriba
  ports:
    - protocol: TCP
      port: 80         # El puerto que recibe el trÃ¡fico del Ingress
      targetPort: 3000 # El puerto hacia donde lo manda (tu App)
