apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextumlabs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextumlabs-app
  template:
    metadata:
      labels:
        app: nextumlabs-app
    spec:
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nextumlabs-backend-service # EL NOMBRE EXACTO QUE BUSCA TU INGRESS
spec:
  type: NodePort
  selector:
    app: nextumlabs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
