apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextumlabs-app
  namespace: nextum-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextumlabs-app
  template:
    metadata:
      labels:
        app: nextumlabs-app
    spec:
      containers:
      - name: nextumlabs-app-container
        image: us-central1-docker.pkg.dev/nextum-labs/nextum-repo/nextumlabs-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nextumlabs-backend-service
  namespace: nextum-dev
spec:
  type: NodePort
  selector:
    app: nextumlabs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
